### PR TITLE
Remove obsolete flags

### PR DESCRIPTION
**Pull request by firasuke**

### CODE REVIEW

**Review by xhebox — COMMENTED** [review]
`libmpx` or `mudflap` does not work with musl at the time of last check. Refer to https://github.com/alpinelinux/aports/blob/6678c5012b50e57721302313feedb36673299114/main/gcc/APKBUILD#L280-L287 . If you really want to remove it, you should provide related materials.

I agreed that `cloog-backend` flag can be removed, though.

**Comment by firasuke** [comment]
`mudflap` was removed from GCC since 4.9 so there's no point in specifying `--disable-libmudflap` as it won't do anything, and `mpx` was removed since 5.6 so specifying `--disable-libmpx` also won't do anything as well.

**Review by xhebox — APPROVED** [review]
Checked, it is true :)

**Comment by firasuke** [comment]
Glad I could help :)

**Pull request merged**
